# http://jekyllrb.com/docs/configuration/
# https://github.com/barryclark/jekyll-now/blob/master/_config.yml

# global configuration
timezone: Etc/UTC

# Site settings
title: Testing Jekyll…
email: offirmo.net@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/github-pages-test" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# http://ajoz.github.io/2014/06/29/i-want-my-github-flavored-markdown/
#markdown: kramdown
markdown: redcarpet
markdown_ext: markdown,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

# extra plugin https://help.github.com/articles/using-jekyll-plugins-with-github-pages/
gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
   - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
   - Gemfile
   - Gemfile.lock
   - README.md

